name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/PersistedValuePackageTests.xctest/Contents/MacOS/PersistedValuePackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
    - name: Sounar Cloud
      run: |
        brew install sonar-scanner
        sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=dimakoroliov -Dsonar.projectKey=PersistedValue -Dsonar.sources=./Sources/PersistedValue
        # xcrun llvm-cov export -format="lcov" .build/debug/PersistedValuePackageTests.xctest/Contents/MacOS/PersistedValuePackageTests -instr-profile .build/debug/codecov/default.profdata > Coverage.report
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
